import {
  Flash,
  Presentation,
  Building,
  Gamepad,
  Trophy,
  Rocket,
  Clock,
  InfoCircle,
} from 'iconoir-react';

export const scheduleItems = [
  {
    time: '08:00 AM',
    title: 'Challenge Announced',
    description:
      'The eSports hackathon challenge is announced. Teams can start working on their projects.',
    icon: Clock,
    color: 'text-primary',
    bgColor: 'bg-primary/10',
  },
  {
    time: '12:00 PM',
    title: 'Competitor Training Onsite',
    description: 'Competitors receive training on the tools and services provided by Hackerrivals.',
    icon: Flash,
    color: 'text-secondary',
    bgColor: 'bg-secondary/10',
  },
  {
    time: '3:00 PM',
    title: 'Round 1: Concept Presentation',
    description: 'eSports hackathon begins! Teams present their innovative concepts',
    icon: Gamepad,
    color: 'text-accent',
    bgColor: 'bg-accent/10',
  },
  {
    time: '03:40 PM',
    title: 'Whammy Announced',
    description: 'The whammy is announced. Teams can continue working on their projects.',
    icon: InfoCircle,
    color: 'text-primary',
    bgColor: 'bg-primary/10',
  },
  {
    time: '03:30 PM',
    title: 'Round 2: MVP Knockout',
    description: 'Intense knockout round - only 2 teams advance to the final!',
    icon: Rocket,
    color: 'text-secondary',
    bgColor: 'bg-secondary/10',
  },
  {
    time: '05:00 PM',
    title: 'Final Round: Main Stage',
    description: 'Polished presentations combining concept, architecture & demo',
    icon: Presentation,
    color: 'text-accent',
    bgColor: 'bg-accent/10',
  },
  {
    time: '05:30 PM',
    title: 'Wrap-up & Prize Ceremony',
    description: 'Winner announcement, $500 cash prize, and charity donation',
    icon: Trophy,
    color: 'text-primary',
    bgColor: 'bg-primary/10',
  },
  {
    time: '06:30 PM',
    title: 'VIP After Party',
    description: 'Exclusive celebration near event venue',
    icon: Building,
    color: 'text-secondary',
    bgColor: 'bg-secondary/10',
  },
];
